### ISSUE TITLE
Support cookiebot data-culture attribute for setting language

### ISSUE THREAD

**Issue by jcsiegrist** [brandcom/silverstripe-analytics#1]
Cookiebot support setting Banner language with the `data-culture` attribute with the two letter language ISO code. 

See https://support.cookiebot.com/hc/en-us/articles/360003793394-How-to-set-the-language-of-the-consent-banner-

and 

https://wissenspool.brandcom.de/link/12#bkmrk-f%C3%BCr-mehrsprachige-si

**Comment by jbennecker** [comment]
ist eingebaut. siehe https://github.com/brandcom/silverstripe-analytics/commit/36c03af65568da6db2bfada8ebd7e627345385e5
